package com.museum;

public enum Actions {
    LOGIN,
    GET_EXHIBITS,
    ADD_EXHIBIT,
    UPDATE_EXHIBIT,
    GET_EXHIBITIONS,
    INSERT_EXHIBITIONS,
    UPDATE_EXHIBITION,
    GET_ROOMS,
    GET_WORKERS_SIMPLIFIED,
    GET_TOURS,
    INSERT_TOUR,
    UPDATE_TOUR,
    GET_WORKERS
}
